version: "2.1"

volumes:
  plex_config:
  prowlarr_config:
  sonarr_config:
  radarr_config:
  qbittorrent_config:
  duckdns_config:

networks:
  docker_network:

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - plex_config:/config
      - /volume1/Data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - docker_network
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - docker_network
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - sonarr_config:/config
      - /volume1/Data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - docker_network
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - radarr_config:/config
      - /volume1/Data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - docker_network
    environment:
      - PUID=1026 #optional
      - PGID=100 #optional
      - SUBDOMAINS=<SUBDOMAIN>
      - TOKEN=<TOKEN>
      - LOG_FILE=true
      - TZ=America/Los_Angeles
    volumes:
      - duckdns_config:/config
    restart: unless-stopped

  openvpn:
    image: ghcr.io/wfg/openvpn-client:latest
    container_name: openvpn
    networks:
      - docker_network
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /volume1/tesseract/openvpn:/data/vpn
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:openvpn
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent_config:/config
      - /volume1/Data:/data
    restart: unless-stopped
    depends_on:
      - openvpn
